#!/bin/bash

BITRATE=
VENCODER=h264_nvenc
FLAGS=-n
DIR=hardsub
STRACK=0
NOFLAC=
FILTER=text
ATRACK=0
INFO=

help () {
  echo "Usage: `basename $0` [[[-b bitrate] [-e] [-y] [-h] [-f] [-p] [-o output_dir] [-s track]] [-z]] files...
-b bitrate         Set target bitrate in bits/sec (default: choose automatically)
-e                 Use HEVC/H.265 encoder (slower)
-y                 Overwrite existing files without asking
-o output_dir      Set the directory for resulting files (will be created if doesn't exist)
-s track           Subtitles track number (use -z to find them)
-a track           Audio track number (use -z to find them)
-f                 Don't autoconvert FLAC audio to AAC
-i                 Print streams information without converting the files
-h                 This help message"
  exit 1
}

dump_streams() {
  RESULT=1
  IDX=0
  while [ -n "$RESULT" ]
  do
    RESULT=$( ffprobe -v error -show_entries stream=codec_name,codec_long_name:stream_tags=title,language -select_streams $1:$IDX -of default=nw=1 "$2" )
    if [ -n "$RESULT" ]
    then
      if [ $IDX -gt 0 ]
      then
        echo "---"
      fi
      echo "index=$IDX"
      echo "$RESULT"
    fi
    IDX=$(( IDX + 1 ))
    done
}

fancy_stars() {
  LEN=$(( ${#1} + 3 ))
  for a in `seq 0 $LEN`
  do
    echo -n "*"
  done
  echo
}

while getopts b:eyho:s:a:fi f
do
  case $f in
    b) BITRATE=$OPTARG
    ;;
    e) VENCODER=hevc_nvenc
    ;;
    y) FLAGS=-y
    ;;
    h) help
    ;;
    o) DIR=$OPTARG
    ;;
    s) STRACK=$OPTARG
    ;;
    a) ATRACK=$OPTARG
    ;;
    f) NOFLAC=1
    ;;
    i) INFO=1
    ;;
  esac
done
shift $(( OPTIND-1 ))

if [ $VENCODER != "hevc_nvenc" ]
then
  FLAGS="$FLAGS -pix_fmt yuv420p -movflags +faststart"
fi

if [ -z "$1" ]
then
  echo "No input files specified"
  exit 1
fi

mkdir -p "$DIR"

FLAGS="$FLAGS -map_chapters -1 -map 0:a:$ATRACK -hide_banner"
for i in "$@"
do
  BN="$(basename "$i")"
  if [ -n "$INFO" ]
  then
    fancy_stars "$BN"
    echo "* $BN *"
    fancy_stars "$BN"
    echo "----- VIDEO -----"
    dump_streams V "$i"
    echo
    echo "----- AUDIO -----"
    dump_streams a "$i"
    echo
    echo "--- SUBTITLES ---"
    dump_streams s "$i"
    echo
  else
    sb=$(esc=$(echo "$i" | sed "s#\([':]\)#\\\\\1#g"); printf "subtitles=%q:si=%d" "$esc" "$STRACK")
    AENCODER=copy
    CODEC=$( ffprobe -v error -show_entries stream=codec_name -select_streams a:$ATRACK -of default=nw=1:nk=1 "$i" )
    [ -z "$NOFLAC" ] && [ "$CODEC" = "flac" ] && AENCODER=aac
    if [ -z "$BITRATE" ]
    then
      CURBITRATE=$(ffprobe -v error -show_entries format=bit_rate -select_streams v -of default=noprint_wrappers=1:nokey=1 "$i")
      CURBITRATE=$(( CURBITRATE / 1000 + 200 ))k
    else
      CURBITRATE=$BITRATE
    fi

    if ffprobe -v error -show_entries stream=codec_name -select_streams s:$STRACK -of default=nw=1:nk=1 "$i" | grep "pgs" >/dev/null
    then
      ffmpeg -i "$i" -sn -c:v "$VENCODER" -b:v "$CURBITRATE" -c:a "$AENCODER" -filter_complex [0:v][0:s:$STRACK]overlay[v] -map [v] $FLAGS "$DIR/$BN"
    else
      ffmpeg -i "$i" -sn -c:v "$VENCODER" -b:v "$CURBITRATE" -c:a "$AENCODER" -vf "$sb" -map 0:v:0 $FLAGS "$DIR/$BN"
    fi
  fi
done
